### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by JerrelS** [Fizcko/sms-gateway#1]
Hi, 

Thx for sharing your python gammu setup.

Im currently using it for a small project, but im having trouble figuring out how to debug new routes I add in the resources.

Short messages are returned on error, but hard to understand. I would like to see a log of the full error python reports.

Any idea how i can accomplish this ?

**Comment by Fizcko** [comment]
Hi,

You have to check flask documentation.

But i think that all message are displayed.

**Comment by Fizcko** [comment]
@JerrelS  Did you find your problem ?

Note that this setup is made for gammu v 1.40.0.

**Comment by JerrelS** [comment]
@Fizcko sorry for the late reply.

I did check the docs, but couldn't figure it out.

Also noticed that some error messages can be seen using  docker-compose logs --follow <fizcko-pyhton-service>, but not all

For example  if the variable P2PMODE is used in one of the routes, without being declared before, the only response i receive from the api  is  **{"details":"P2PMODE","message":"Internal error"}** , while python itself would report a more detailed message in the terminal. see below

**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'P2PMODE' is not defined**

My thought was that maybe the debug level of flask had to be increased, so I played around with some options in the server/instance.py  changed logger.setLevel(logging.INFO) to logger.setLevel(logging.DEBUG) but still no luck receiving more details in the error response

Yes de default setup is for 1.40.0 but upgraded it to 1.41 on debian:sid-slim. Waiting for gammu v 1.42 to become available or this dist.

**Comment by Fizcko** [comment]
You can modify resources>errors.py like this

```
import traceback
from server.instance import server
from werkzeug.exceptions import HTTPException

app = server.app
jwt = server.jwt

@app.errorhandler
def default_error_handler(error):
    return {"message": "Internal error",'details': str(error)}, 500

@app.errorhandler(Exception)
def default_exception_handler(error):
    if isinstance(error, HTTPException):
        return {"message": "Internal error",'details': str(error)}, 500
    else:
        infos = traceback.format_exc()
        return {"message": "Internal error",'details': str(infos)}, 500

@app.errorhandler(404)
def resource_not_found(err):
    return {"message": "Page not found",'details': str(err)}, 404
```

to display the python error message in the json result

**Comment by JerrelS** [comment]
Many tx it works, it spits out a bit more then I need (o: but it gets that job done. now i can see a line number and file name

Below is a new sample of the error output.

Much appreciated.

P.s do you by any chance also have the skills to add new (not yet supported) modems to python-gammu?




{
    "details": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1950, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1936, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/usr/local/lib/python3.9/dist-packages/flask_restplus/api.py\", line 325, in wrapper\n    resp = resource(*args, **kwargs)\n  File \"/usr/local/lib/python3.9/dist-packages/flask/views.py\", line 89, in view\n    return self.dispatch_request(*args, **kwargs)\n  File \"/usr/local/lib/python3.9/dist-packages/flask_restplus/resource.py\", line 44, in dispatch_request\n    resp = meth(*args, **kwargs)\n  File \"/usr/local/lib/python3.9/dist-packages/flask_jwt_extended/view_decorators.py\", line 108, in wrapper\n    return fn(*args, **kwargs)\n  **File \"/opt/sms_gateway/resources/v1/routes.py\", line 135, in post\n    lastInboxID = getInboxID(self,'')\n  File \"/opt/sms_gateway/myfunctions/generalfunctions.py\", line 291, in getInboxID\n    mycursor = db.cursor()\nNameError: name 'db' is not defined\n",**
    "message": "Internal error"
}

**Comment by Fizcko** [comment]
Great news.

Sorry but i don't have skills to add new modems.

Good luck for your project

**Comment by JerrelS** [comment]
Ok, np (o:
