### ISSUE TITLE
/v1/login route doesn't work

### ISSUE THREAD

**Issue by luckysimek** [Fizcko/sms-gateway#2]
payload:
{
  "username": "smsapi",
  "password": "d5c95Gt4EN"
}

response:
{
  "details": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1950, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1936, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/usr/local/lib/python3.7/dist-packages/flask_restplus/api.py\", line 325, in wrapper\n    resp = resource(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/dist-packages/flask/views.py\", line 89, in view\n    return self.dispatch_request(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/dist-packages/flask_restplus/resource.py\", line 44, in dispatch_request\n    resp = meth(*args, **kwargs)\n  File \"/opt/sms_gateway/resources/v1/auth.py\", line 30, in post\n    access_token = create_access_token(identity=username)\n  File \"/usr/local/lib/python3.7/dist-packages/flask_jwt_extended/utils.py\", line 173, in create_access_token\n    headers=headers)\n  File \"/usr/local/lib/python3.7/dist-packages/flask_jwt_extended/jwt_manager.py\", line 522, in _create_access_token\n    headers=headers\n  File \"/usr/local/lib/python3.7/dist-packages/flask_jwt_extended/tokens.py\", line 77, in encode_access_token\n    json_encoder=json_encoder, headers=headers)\n  File \"/usr/local/lib/python3.7/dist-packages/flask_jwt_extended/tokens.py\", line 30, in _encode_jwt\n    json_encoder=json_encoder, headers=headers).decode('utf-8')\nAttributeError: 'str' object has no attribute 'decode'\n",
  "message": "Internal error"
}

**Comment by Fizcko** [comment]
Are you sending the payload in JSON content Type and UTF8 ?

**Comment by luckysimek** [comment]
I'm using swager UI, content is utf8 for sure, content type app/json
---------------------------------------
Pozdrawiam / Best regards
Simek :)


czw., 9 wrz 2021 o 08:49 Fizcko ***@***.***> napisał(a):

**Comment by Fizcko** [comment]
I can't reproduce the bug.
It seems to be a bug with flask

**Comment by Fizcko** [comment]
Hi @luckysimek 

I've publish some update : 

Update Flask, Waitress
Use now flask-restx and no more flask-restplus
Add multiple authentication methods

Maybe this will  resolved your issue
